
# Our web container
web:

  # Root directory is built
  build: ../containers/api

  # Start it up
  command: npm start

  # Mount volume of local files
  volumes:
    - "../containers/api:/src/"

  # Map machines port 80 with container's 3000
  ports:
    - "80:3000"

  # Link to our mysql container
  links:
    - mysql

# Our MySQL container
mysql:

  # Grab the latest mysql image from Docker
  image: tutum/mysql:latest

  # Set port to default mysql port
  ports: 
    - "3306:3306"

  # Mount volume of local files
  volumes:
    - "../containers/db:/src"

  # Set up environment variables
  environment:
    MYSQL_USER: admin
    MYSQL_PASS: admin
    ON_CREATE_DB: docker_demo
    STARTUP_SQL: /src/tmp/seed.sql